name: CI

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  checks:
    name: Pre-merge Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/step-node@v4

      - name: Setup
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Test build
        run: npm run build
