name: Release

on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      - name: Publish
        run: npm publish --tag latest --access=public --provenance
